import os
import logging
from datetime import datetime
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from typing import Dict, List, Any

logger = logging.getLogger(__name__)

class ReportGenerator:
    """Generates immutable PDF artifacts for executive-level compliance and reporting.
    
    Converts ephemeral dashboard states into standardized document formats
    suitable for boardroom presentation and long-term archiving.
    """
    
    def __init__(self, output_dir: str = "reports"):
        """Initializes the report engine.
        
        Args:
            output_dir (str): Destination directory for generated PDFs.
        """
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_pdf(self, kpis: Dict[str, Any], ai_insights: str) -> str:
        """Synthesizes a multi-section PDF report.
        
        Args:
            kpis (Dict): Metric dictionary.
            ai_insights (str): Markdown or text insights generated by the AI agent.
            
        Returns:
            str: Absolute path to the generated PDF file.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"HR_Strategic_Report_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        logger.info(f"Initiating PDF synthesis for: {filepath}")
        
        try:
            c = canvas.Canvas(filepath, pagesize=LETTER)
            width, height = LETTER

            # Header Section
            c.setFont("Helvetica-Bold", 18)
            c.drawString(70, height - 60, "Strategic Human Capital Analysis")
            
            c.setFont("Helvetica", 9)
            c.setFillGray(0.3)
            c.drawString(70, height - 75, f"Report generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            c.setFillGray(0) # Reset to black
            
            # --- 1. KPI Summary Section ---
            c.setStrokeColor(colors.lightgrey)
            c.line(70, height - 90, width - 70, height - 90)
            
            c.setFont("Helvetica-Bold", 13)
            c.drawString(70, height - 110, "1. Executive KPI Summary")
            
            c.setFont("Helvetica", 11)
            y = height - 135
            metrics = [
                ("Total Headcount", kpis.get('headcount')),
                ("Employee Attrition", f"{kpis.get('attrition_rate')}%"),
                ("Average Age", kpis.get('average_age')),
                ("Average Tenure", f"{kpis.get('average_tenure')} Years")
            ]
            
            for label, val in metrics:
                c.drawString(90, y, f"• {label}:")
                c.drawRightString(width - 90, y, str(val))
                y -= 20
            
            # --- 2. AI Assessment Section ---
            y -= 20
            c.setFont("Helvetica-Bold", 13)
            c.drawString(70, y, "2. Augmented Risk Assessment & Recommendations")
            
            y -= 25
            text_object = c.beginText(70, y)
            text_object.setFont("Helvetica", 9)
            text_object.setLeading(12)
            
            # Simplified wrapping for non-TrueType fonts
            wrapped_content = self._wrap_text(ai_insights, 95)
            for line in wrapped_content:
                if y < 80: # Multi-page check (simplified)
                    c.drawText(text_object)
                    c.showPage()
                    y = height - 60
                    text_object = c.beginText(70, y)
                    text_object.setFont("Helvetica", 9)
                    
                text_object.textLine(line)
                y -= 12
            
            c.drawText(text_object)
            c.showPage()
            c.save()
            
            logger.info("PDF report successfully archived.")
            return filepath
        except Exception as e:
            logger.error(f"Failed to generate report: {str(e)}")
            raise

    def _wrap_text(self, text: str, width: int) -> List[str]:
        """Sub-optimal but robust text wrapper for basic PDF generation."""
        lines = []
        for paragraph in text.split('\n'):
            if not paragraph.strip():
                lines.append("")
                continue
            
            # Naive wrap
            while len(paragraph) > width:
                lines.append(paragraph[:width])
                paragraph = paragraph[width:]
            lines.append(paragraph)
        return lines
